### ISSUE TITLE
better README

### ISSUE THREAD

**Issue by michalbcz** [dave-hal/UrlShort#7]
Imho README should have those sections:

1) about - what is the project about, why you should use it
2) how to develop/start it like mvn spring-boot:run (see https://docs.spring.io/spring-boot/docs/current/reference/html/using-spring-boot.html#using-boot-running-your-application)
3) usage (examples) - in your case i would appreciate some description of api - easiest way is imho use curl examples (eg. use Insomnia tool to create examples and you can export curl from them - see https://support.insomnia.rest/article/37-code-snippet-generation)

You can use checkout some opensource projects for inspiration.
https://github.com/eslint/eslint
https://github.com/keycloak/keycloak
https://github.com/khoubyari/spring-boot-rest-example

**Comment by dave-hal** [comment]
7f2e6592dda10b136a7db7a79be9a4010d07bb2e commit
